# Reference https://mybinder.readthedocs.io/en/latest/howto/gh-actions-badges.html
name: Test this PR on Binder Badge

on:
  pull_request_target:
    types: [opened]

jobs:
  binder:
    uses: eds-book/notebooks-workflows/.github/workflows/binder.yaml@main